classdef wallpaperDLY < audioPlugin
    properties
        time = 100;
        fb = 1;
        high = 500;
        low = 2000;
        on = false;
        mix = 75;
       
        
    end
    properties (Constant)
        fs = 44100;
        
   PluginInterface = audioPluginInterface(...
       audioPluginParameter('time',...
       'Layout',[2,1],...
       'DisplayName','TIME',...
       'DisplayNameLocation','Above',...
       'Style','rotaryknob',...
       'Label','ms',...
       'Mapping',{'lin',1,2000}),...
      audioPluginParameter('fb',...
      'Layout',[2,2],...
        'DisplayName','REPEAT',...
        'DisplayNameLocation','Above',...
        'Style','rotaryknob',...
        'Label','%',...
        'Mapping',{'lin',1,99}),...
      audioPluginParameter('high',...
      'Layout',[2,3],...
        'DisplayName','HIGH',...
        'DisplayNameLocation','Above',...
        'Style','rotaryknob',...
        'Label','Hz',...
        'Mapping',{'lin',40,1000}),...
        audioPluginParameter('low',...
        'Layout',[2,4],...
        'DisplayName','LOW',...
        'DisplayNameLocation','Above',...
        'Style','rotaryknob',...
        'Label','Hz',...
        'Mapping',{'lin',500,5000}),...
        audioPluginParameter('on',...
        'Layout',[2,5],...
        'DisplayName','ON',...
        'DisplayNameLocation','Above',...
        'Style','vtoggle'),...
        audioPluginParameter('mix',...
      'Layout',[3,3],...
        'DisplayName','MIX',...
        'DisplayNameLocation','Below',...
        'Style','rotaryknob',...
        'Label','DRY/WET',...
        'Mapping',{'lin',1,100}),...
        ...
        'BackgroundImage','wallpaper.png',...
        audioPluginGridLayout(...
        'RowHeight',[142,130,130,80],...
        'ColumnWidth',[98,98,98,98,98],...
        'RowSpacing',10))
    end
    methods
        function process(plugin, in)
        if (on == true)
         for x = 1:N
         out =  in(x,1) + feed * time(end,1);  
         
         end 
     else 
         out = in;
    end
        end 
    end
end